name: Team Group-P7-06 CI tasks
on:
  push:
     branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: backend/SuperPrice
        run: ./mvnw --batch-mode --update-snapshots package
  
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v3
     
      - name: Install dependinces 
        working-directory: front-end 
        run: npm install

      - name: Run tests 
        working-directory: front-end  
        run: npm test

      - name: Build
        working-directory: front-end  
        run: npm run build